apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: yonatanlevin/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: yonatanlevin/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: yonatanlevin/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: yonatanlevin/ticketing-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .  
    - image: yonatanlevin/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .  
    - image: yonatanlevin/ticketing-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .  
# ---
# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   # local:
#   #   push: false
#   googleCloudBuild:
#     projectId: ticketing-dev-372517
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-372517/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: "src/**/*.ts"
#             dest: .